name: yangzj
age: 18
#flag: true

date: 2020-03-23

person1: {name:yangzj, age:18}

person2:
    name: yangzj
    age: 18

list1: [a, b, c]

list2:
    - a
    - b
    - c

persons:
    - name: yangzj
      age: 18
    - name: zhangsan
      age: 20
    - {name:lisi, age:25}

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      # 发送的对象信息变为json格式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2


